"""Initial migration

Revision ID: e09c4f3482ae
Revises: 
Create Date: 2026-04-08 23:28:04.415445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09c4f3482ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=False),
    sa.Column('fk_notes_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_notes_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
